version: '2'

services:
  shared_volumes:
    image: busybox
    volumes:
      - ./config/test.json:/opt/orbs/config/test.json
      - ./e2e:/opt/orbs/e2e
      - ./projects/services/public-api-service-typescript/dist:/opt/orbs/projects/services/public-api-service-typescript/dist
      - ./projects/services/sidechain-connector-service-typescript/dist:/opt/orbs/projects/services/sidechain-connector-service-typescript/dist
      - ./projects/services/storage-service-typescript/dist:/opt/orbs/projects/services/storage-service-typescript/dist
      - ./projects/services/consensus-service-typescript/dist:/opt/orbs/projects/services/consensus-service-typescript/dist
      - ./projects/services/virtual-machine-service-typescript/dist:/opt/orbs/projects/services/virtual-machine-service-typescript/dist
